### ISSUE TITLE
Client side scanning

### ISSUE THREAD

**Issue by ktomingas** [jimmytidey/bibnet-google-scholar-scraper#4]
HI Jimmy,

I tested two-three latest versions but I can't get running the client side scraping with Chrome extension. Client app seems to be working, Google Scholar responses also (according to console), but there are no any responses from server side and no authors or publications added to database/screen. What could be wrong in app or my conf/env (I am not familiar with Meteor)? 
By the way, the last version with server side scanning works well, at least until Google will stop answering with robot check.

Thanks,
K

**Comment by jimmytidey** [comment]
Ah - yes this is why people use branches! 

If you do 
`git checkout b472441a7c8465af6a892da607ed13c22c5d52ca`

That should take you back to the latest version that works properly. 

I'll branch this dev work off separately so that people can carry on using the old version shortly.

**Comment by emdalton** [comment]
I tried doing this checkout, but now it's throwing an error on the command line:

.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENOSPC: no space left on device, write
    at Error (native)
 => awaited here:
    at Promise.await (/home/zigraphix/.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:39:12)
    at Object.wrapper [as writeFile](/tools/fs/files.js:1522:32)
    at /tools/isobuild/builder.js:501:17
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:456:34)
    at /tools/isobuild/builder.js:485:13
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:456:34)
    at /tools/isobuild/builder.js:485:13
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:456:34)
    at /tools/isobuild/builder.js:485:13
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:456:34)
    at Builder.copyDirectory (/tools/isobuild/builder.js:512:5)
    at /tools/isobuild/isopack.js:1484:17
    at Array.forEach (native)
    at Function._.each._.forEach (/home/zigraphix/.meteor/packages/meteor-tool/.1.4.2.1r0536n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack.js:1480:9
    at Isopack.saveToPath (/tools/isobuild/isopack.js:1191:9)
    at [object Object]._saveIsopack (/tools/packaging/tropohouse.js:353:15)
    at /tools/packaging/tropohouse.js:526:16
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/packaging/tropohouse.js:515:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.download (/tools/packaging/tropohouse.js:427:20)
    at /tools/packaging/tropohouse.js:600:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object].downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:597:20)
    at /tools/cli/main.js:462:30
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at /tools/cli/main.js:461:17
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at /tools/cli/main.js:459:33
    at Console.withProgressDisplayVisible (/tools/console/console.js:633:14)
    at springboard (/tools/cli/main.js:458:11)
    at /tools/cli/main.js:1097:5

With the master branch, I get the server running and I can connect to it with Chromium (not Firefox), and a search creates the popup with results, but nothing gets added to the Chromium window and the terminal chatter suggests that nothing is being added to the database, either.

This looks like a really cool tool and I'd like to try running my dissertation references through it....
