### ISSUE TITLE
bibnet ‘is crashing’

### ISSUE THREAD

**Issue by Anaphory** [jimmytidey/bibnet-google-scholar-scraper#6]
I cloned the repository,and tried to run bibnet, with the following result:

    W20180804-20:50:34.918(2)? (STDERR) /home/gereon/devel/bibnet/.meteor/local/build/programs/server/boot.js:475
    W20180804-20:50:34.919(2)? (STDERR) }).run();
    W20180804-20:50:34.919(2)? (STDERR)    ^
    W20180804-20:50:34.920(2)? (STDERR) 
    W20180804-20:50:34.920(2)? (STDERR) Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
    W20180804-20:50:34.920(2)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
    => Exited with code: 1

Getting to that stage was not straightforward, either. I cloned the repository, and then ran the following commands (with that output). If I knew anything at all about `meteor`, I might try to dig up what might cause the error (changes in packages?).
```
~/d/bibnet » meteor
[[[[[ ~/devel/bibnet ]]]]]                    

=> Started proxy.                             
=> A patch (Meteor 1.4.4.6) for your current release is available!
   Update this project now with 'meteor update --patch'.
Unexpected mongo exit code 1. Restarting.     
Unexpected mongo exit code 1. Restarting.     
Unexpected mongo exit code 1. Restarting.     
Can't start Mongo server.                     
MongoDB failed global initialization

Looks like MongoDB doesn't understand your locale settings. See
https://github.com/meteor/meteor/issues/4019 for more details.
```
Assuming the update is a good idea, and checking my `locale` setting, then running `meteor` again.
```
~/d/bibnet » meteor update --patch
bibnet: updated to Meteor 1.4.4.6.            
~/d/bibnet » env | grep '\(LC_\|LANG\)' -i
LANG=en_GB.UTF-8
~/d/bibnet » LANG=C meteor
[[[[[ ~/devel/bibnet ]]]]]                    

=> Started proxy.                             
=> Meteor 1.7.0.3 is available. Update this project with 'meteor update'.
Unexpected mongo exit code 1. Restarting.     
Unexpected mongo exit code 1. Restarting.     
Unexpected mongo exit code 1. Restarting.     
Can't start Mongo server.                     
MongoDB failed global initialization

Looks like MongoDB doesn't understand your locale settings. See
https://github.com/meteor/meteor/issues/4019 for more details.
```
Okay, the locale seems to be a red herring, let me run this mysterious update.
```
~/d/bibnet » meteor update
bibnet: updated to Meteor 1.7.0.3.            
                                                                                   
Changes to your project's package version selections from updating package versions:
                                              
ecmascript-runtime-client  upgraded from 0.7.1 to 0.7.2
ecmascript-runtime-server  upgraded from 0.7.0 to 0.7.1

                                              
The following top-level dependencies were not updated to the very latest version available:
 * aldeed:collection2 2.10.0 (3.0.0 is available)
 * aldeed:tabular 1.6.1 (2.1.1 is available)  
 * okgrow:analytics 2.1.3 (3.0.5 is available)
                                              
Newer versions of the following indirect dependencies are available:
 * aldeed:collection2-core 1.2.0 (2.1.2 is available)
 * aldeed:schema-deny 1.1.0 (3.0.0 is available)
 * aldeed:schema-index 1.1.1 (3.0.0 is available)
 * coffeescript 1.0.17 (2.2.1_1 is available) 
 * softwarerero:accounts-t9n 1.3.11 (2.3.1 is available)
These versions may not be compatible with your project.
To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`,
or just run `meteor update --all-packages`.
~/d/bibnet » meteor
[[[[[ ~/devel/bibnet ]]]]]                    

=> Started proxy.                             
=> Started MongoDB.                           
W20180804-20:50:30.115(2)? (STDERR) /home/gereon/devel/bibnet/.meteor/local/build/programs/server/boot.js:475
W20180804-20:50:30.255(2)? (STDERR) }).run();
W20180804-20:50:30.255(2)? (STDERR)    ^
W20180804-20:50:30.256(2)? (STDERR) 
W20180804-20:50:30.256(2)? (STDERR) Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
W20180804-20:50:30.256(2)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180804-20:50:30.256(2)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180804-20:50:30.256(2)? (STDERR)     at Object.require (/home/gereon/devel/bibnet/.meteor/local/build/programs/server/boot.js:288:32)
W20180804-20:50:30.257(2)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:604:18)
W20180804-20:50:30.257(2)? (STDERR)     at Module.require (packages/modules-runtime.js:230:14)
W20180804-20:50:30.257(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180804-20:50:30.257(2)? (STDERR)     at livedata_connection.js (/home/gereon/devel/bibnet/.meteor/local/build/programs/server/packages/ddp-client.js:147:30)
W20180804-20:50:30.257(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180804-20:50:30.258(2)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180804-20:50:30.258(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
=> Exited with code: 1
W20180804-20:50:33.378(2)? (STDERR) /home/gereon/devel/bibnet/.meteor/local/build/programs/server/boot.js:475
W20180804-20:50:33.380(2)? (STDERR) }).run();
W20180804-20:50:33.380(2)? (STDERR)    ^
W20180804-20:50:33.381(2)? (STDERR) 
W20180804-20:50:33.381(2)? (STDERR) Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
W20180804-20:50:33.381(2)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180804-20:50:33.382(2)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180804-20:50:33.382(2)? (STDERR)     at Object.require (/home/gereon/devel/bibnet/.meteor/local/build/programs/server/boot.js:288:32)
W20180804-20:50:33.382(2)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:604:18)
W20180804-20:50:33.382(2)? (STDERR)     at Module.require (packages/modules-runtime.js:230:14)
W20180804-20:50:33.383(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180804-20:50:33.383(2)? (STDERR)     at livedata_connection.js (/home/gereon/devel/bibnet/.meteor/local/build/programs/server/packages/ddp-client.js:147:30)
W20180804-20:50:33.383(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180804-20:50:33.383(2)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180804-20:50:33.384(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
=> Exited with code: 1
W20180804-20:50:34.918(2)? (STDERR) /home/gereon/devel/bibnet/.meteor/local/build/programs/server/boot.js:475
W20180804-20:50:34.919(2)? (STDERR) }).run();
W20180804-20:50:34.919(2)? (STDERR)    ^
W20180804-20:50:34.920(2)? (STDERR) 
W20180804-20:50:34.920(2)? (STDERR) Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
W20180804-20:50:34.920(2)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180804-20:50:34.920(2)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180804-20:50:34.921(2)? (STDERR)     at Object.require (/home/gereon/devel/bibnet/.meteor/local/build/programs/server/boot.js:288:32)
W20180804-20:50:34.921(2)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:604:18)
W20180804-20:50:34.921(2)? (STDERR)     at Module.require (packages/modules-runtime.js:230:14)
W20180804-20:50:34.921(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180804-20:50:34.922(2)? (STDERR)     at livedata_connection.js (/home/gereon/devel/bibnet/.meteor/local/build/programs/server/packages/ddp-client.js:147:30)
W20180804-20:50:34.922(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180804-20:50:34.922(2)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180804-20:50:34.922(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```
What should I do now?

**Comment by Anaphory** [comment]
Following [this question on StackOverflow](https://stackoverflow.com/q/51684918/1274613), the issue is with the most recent `beta` version of babel runtime. Changing the corresponding line in `package.json` to

    "@babel/runtime": "^7.0.0-beta.55",

and running
    $ meteor npm install @babel/runtime@7.0.0-beta.55

made `meteor` start properly:
```
~/d/bibnet » meteor
[[[[[ ~/devel/bibnet ]]]]]                    

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```
